{
  "Header": {
    "Original": "CVE-2021-28677 (An issue was discovered in Pillow before 8.2.0. For EPS data, the read ...)",
    "Line": 165890,
    "ID": "CVE-2021-28677",
    "Description": "(An issue was discovered in Pillow before 8.2.0. For EPS data, the read ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2716-1}",
      "Line": 165891,
      "Type": "xref",
      "Bugs": [
        "DLA-2716-1"
      ]
    },
    {
      "Original": "[experimental] - pillow 8.2.0-1",
      "Line": 165892,
      "Type": "package",
      "Release": "experimental",
      "Package": "pillow",
      "Kind": "fixed",
      "Version": "8.2.0-1"
    },
    {
      "Original": "- pillow 8.1.2+dfsg-0.2 (bug #989062)",
      "Line": 165893,
      "Type": "package",
      "Package": "pillow",
      "Kind": "fixed",
      "Version": "8.1.2+dfsg-0.2",
      "BugNo": 989062
    },
    {
      "Original": "[buster] - pillow 5.4.1-2+deb10u3",
      "Line": 165894,
      "Type": "package",
      "Release": "buster",
      "Package": "pillow",
      "Kind": "fixed",
      "Version": "5.4.1-2+deb10u3"
    },
    {
      "Original": "NOTE: https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28677-fix-eps-dos-on-open",
      "Line": 165895,
      "Type": "NOTE",
      "Description": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28677-fix-eps-dos-on-open"
    },
    {
      "Original": "NOTE: https://github.com/python-pillow/Pillow/commit/5a5e6db0abf4e7a638fb1b3408c4e495a096cb92",
      "Line": 165896,
      "Type": "NOTE",
      "Description": "https://github.com/python-pillow/Pillow/commit/5a5e6db0abf4e7a638fb1b3408c4e495a096cb92"
    }
  ]
}