{
  "Header": {
    "Original": "CVE-2021-33430 (A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_N ...)",
    "Line": 153428,
    "ID": "CVE-2021-33430",
    "Description": "(A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_N ...)"
  },
  "Annotations": [
    {
      "Original": "- numpy 1:1.21.4-2",
      "Line": 153429,
      "Type": "package",
      "Package": "numpy",
      "Kind": "fixed",
      "Version": "1:1.21.4-2"
    },
    {
      "Original": "[bullseye] - numpy \u003cno-dsa\u003e (Minor issue)",
      "Line": 153430,
      "Type": "package",
      "Release": "bullseye",
      "Package": "numpy",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/numpy/numpy/issues/18939",
      "Line": 153431,
      "Type": "NOTE",
      "Description": "https://github.com/numpy/numpy/issues/18939"
    },
    {
      "Original": "NOTE: https://github.com/numpy/numpy/pull/18989",
      "Line": 153432,
      "Type": "NOTE",
      "Description": "https://github.com/numpy/numpy/pull/18989"
    },
    {
      "Original": "NOTE: https://github.com/numpy/numpy/commit/16f7824b4d935b6aee98298ca4123d57174a6f2e (v1.22.0.dev0)",
      "Line": 153433,
      "Type": "NOTE",
      "Description": "https://github.com/numpy/numpy/commit/16f7824b4d935b6aee98298ca4123d57174a6f2e (v1.22.0.dev0)"
    }
  ]
}