{
  "Header": {
    "Original": "CVE-2018-5783 (In PoDoFo 0.9.5, there is an uncontrolled memory allocation in the PoD ...)",
    "Line": 362723,
    "ID": "CVE-2018-5783",
    "Description": "(In PoDoFo 0.9.5, there is an uncontrolled memory allocation in the PoD ...)"
  },
  "Annotations": [
    {
      "Original": "- libpodofo 0.9.6+dfsg-4 (bug #916142)",
      "Line": 362724,
      "Type": "package",
      "Package": "libpodofo",
      "Kind": "fixed",
      "Version": "0.9.6+dfsg-4",
      "BugNo": 916142
    },
    {
      "Original": "[stretch] - libpodofo \u003cno-dsa\u003e (Minor issue)",
      "Line": 362725,
      "Type": "package",
      "Release": "stretch",
      "Package": "libpodofo",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[jessie] - libpodofo \u003cno-dsa\u003e (Minor issue)",
      "Line": 362726,
      "Type": "package",
      "Release": "jessie",
      "Package": "libpodofo",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[wheezy] - libpodofo \u003cno-dsa\u003e (Minor issue)",
      "Line": 362727,
      "Type": "package",
      "Release": "wheezy",
      "Package": "libpodofo",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://sourceforge.net/p/podofo/tickets/4/",
      "Line": 362728,
      "Type": "NOTE",
      "Description": "https://sourceforge.net/p/podofo/tickets/4/"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1536179",
      "Line": 362729,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1536179"
    },
    {
      "Original": "NOTE: https://sourceforge.net/p/podofo/code/1949",
      "Line": 362730,
      "Type": "NOTE",
      "Description": "https://sourceforge.net/p/podofo/code/1949"
    }
  ]
}