{
  "Header": {
    "Original": "CVE-2020-26566 (A Denial of Service condition in Motion-Project Motion 3.2 through 4.3 ...)",
    "Line": 202243,
    "ID": "CVE-2020-26566",
    "Description": "(A Denial of Service condition in Motion-Project Motion 3.2 through 4.3 ...)"
  },
  "Annotations": [
    {
      "Original": "- motion 4.3.2-1 (bug #972986)",
      "Line": 202244,
      "Type": "package",
      "Package": "motion",
      "Kind": "fixed",
      "Version": "4.3.2-1",
      "BugNo": 972986
    },
    {
      "Original": "[buster] - motion \u003cnot-affected\u003e (Vulnerable code introduced in 4.2)",
      "Line": 202245,
      "Type": "package",
      "Release": "buster",
      "Package": "motion",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced in 4.2"
    },
    {
      "Original": "[stretch] - motion \u003cnot-affected\u003e (Vulnerable code introduced in 4.2)",
      "Line": 202246,
      "Type": "package",
      "Release": "stretch",
      "Package": "motion",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced in 4.2"
    },
    {
      "Original": "NOTE: https://github.com/Motion-Project/motion/security/advisories/GHSA-6f7x-grw7-fw24",
      "Line": 202247,
      "Type": "NOTE",
      "Description": "https://github.com/Motion-Project/motion/security/advisories/GHSA-6f7x-grw7-fw24"
    },
    {
      "Original": "NOTE: https://github.com/Motion-Project/motion/issues/1227#issuecomment-715927776",
      "Line": 202248,
      "Type": "NOTE",
      "Description": "https://github.com/Motion-Project/motion/issues/1227#issuecomment-715927776"
    },
    {
      "Original": "NOTE: https://github.com/Motion-Project/motion/pull/1232",
      "Line": 202249,
      "Type": "NOTE",
      "Description": "https://github.com/Motion-Project/motion/pull/1232"
    }
  ]
}