{
  "Header": {
    "Original": "CVE-2017-12960 (There is a reachable assertion abort in the function dict_rename_var() ...)",
    "Line": 395306,
    "ID": "CVE-2017-12960",
    "Description": "(There is a reachable assertion abort in the function dict_rename_var() ...)"
  },
  "Annotations": [
    {
      "Original": "- pspp 1.0.1-1 (unimportant)",
      "Line": 395307,
      "Type": "package",
      "Package": "pspp",
      "Kind": "fixed",
      "Version": "1.0.1-1",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1482433",
      "Line": 395308,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1482433"
    },
    {
      "Original": "NOTE: Crash in CLI tool, no security impact",
      "Line": 395309,
      "Type": "NOTE",
      "Description": "Crash in CLI tool, no security impact"
    }
  ]
}