{
  "Header": {
    "Original": "CVE-2021-36368 (An issue was discovered in OpenSSH before 8.9. If a client is using pu ...)",
    "Line": 147494,
    "ID": "CVE-2021-36368",
    "Description": "(An issue was discovered in OpenSSH before 8.9. If a client is using pu ...)"
  },
  "Annotations": [
    {
      "Original": "- openssh 1:8.9p1-1 (unimportant)",
      "Line": 147495,
      "Type": "package",
      "Package": "openssh",
      "Kind": "fixed",
      "Version": "1:8.9p1-1",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://bugzilla.mindrot.org/show_bug.cgi?id=3316",
      "Line": 147496,
      "Type": "NOTE",
      "Description": "https://bugzilla.mindrot.org/show_bug.cgi?id=3316"
    },
    {
      "Original": "NOTE: https://docs.ssh-mitm.at/trivialauth.html",
      "Line": 147497,
      "Type": "NOTE",
      "Description": "https://docs.ssh-mitm.at/trivialauth.html"
    }
  ]
}