{
  "Header": {
    "Original": "CVE-2020-25636 (A flaw was found in Ansible Base when using the aws_ssm connection plu ...)",
    "Line": 203728,
    "ID": "CVE-2020-25636",
    "Description": "(A flaw was found in Ansible Base when using the aws_ssm connection plu ...)"
  },
  "Annotations": [
    {
      "Original": "- ansible \u003cnot-affected\u003e (Vulnerable connection/aws_ssm plugin not included)",
      "Line": 203729,
      "Type": "package",
      "Package": "ansible",
      "Kind": "not-affected",
      "Description": "Vulnerable connection/aws_ssm plugin not included"
    },
    {
      "Original": "NOTE: https://github.com/ansible-collections/community.aws/issues/221",
      "Line": 203730,
      "Type": "NOTE",
      "Description": "https://github.com/ansible-collections/community.aws/issues/221"
    }
  ]
}