{
  "Header": {
    "Original": "CVE-2020-27768 (In ImageMagick, there is an outside the range of representable values  ...)",
    "Line": 198288,
    "ID": "CVE-2020-27768",
    "Description": "(In ImageMagick, there is an outside the range of representable values  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3357-1 DLA-2602-1}",
      "Line": 198289,
      "Type": "xref",
      "Bugs": [
        "DLA-3357-1",
        "DLA-2602-1"
      ]
    },
    {
      "Original": "- imagemagick 8:6.9.11.24+dfsg-1",
      "Line": 198290,
      "Type": "package",
      "Package": "imagemagick",
      "Kind": "fixed",
      "Version": "8:6.9.11.24+dfsg-1"
    },
    {
      "Original": "NOTE: https://github.com/ImageMagick/ImageMagick/issues/1751",
      "Line": 198291,
      "Type": "NOTE",
      "Description": "https://github.com/ImageMagick/ImageMagick/issues/1751"
    },
    {
      "Original": "NOTE: ImageMagick: https://github.com/ImageMagick/ImageMagick/commit/95d4e94e0353e503b71a53f5e6fad173c7c70c90",
      "Line": 198292,
      "Type": "NOTE",
      "Description": "ImageMagick: https://github.com/ImageMagick/ImageMagick/commit/95d4e94e0353e503b71a53f5e6fad173c7c70c90"
    },
    {
      "Original": "NOTE: ImageMagick6: https://github.com/ImageMagick/ImageMagick6/commit/8c6e86f81968fab1710317d87b00c608108e6a2a",
      "Line": 198293,
      "Type": "NOTE",
      "Description": "ImageMagick6: https://github.com/ImageMagick/ImageMagick6/commit/8c6e86f81968fab1710317d87b00c608108e6a2a"
    }
  ]
}