{
  "Header": {
    "Original": "CVE-2019-10742 (Axios up to and including 0.18.0 allows attackers to cause a denial of ...)",
    "Line": 294152,
    "ID": "CVE-2019-10742",
    "Description": "(Axios up to and including 0.18.0 allows attackers to cause a denial of ...)"
  },
  "Annotations": [
    {
      "Original": "- node-axios 0.17.1+dfsg-2 (bug #928624)",
      "Line": 294153,
      "Type": "package",
      "Package": "node-axios",
      "Kind": "fixed",
      "Version": "0.17.1+dfsg-2",
      "BugNo": 928624
    },
    {
      "Original": "NOTE: https://app.snyk.io/vuln/SNYK-JS-AXIOS-174505",
      "Line": 294154,
      "Type": "NOTE",
      "Description": "https://app.snyk.io/vuln/SNYK-JS-AXIOS-174505"
    },
    {
      "Original": "NOTE: https://github.com/axios/axios/issues/1098",
      "Line": 294155,
      "Type": "NOTE",
      "Description": "https://github.com/axios/axios/issues/1098"
    },
    {
      "Original": "NOTE: https://github.com/axios/axios/pull/1485",
      "Line": 294156,
      "Type": "NOTE",
      "Description": "https://github.com/axios/axios/pull/1485"
    }
  ]
}