{
  "Header": {
    "Original": "CVE-2016-0740 (Buffer overflow in the ImagingLibTiffDecode function in libImaging/Tif ...)",
    "Line": 461767,
    "ID": "CVE-2016-0740",
    "Description": "(Buffer overflow in the ImagingLibTiffDecode function in libImaging/Tif ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-3499-1}",
      "Line": 461768,
      "Type": "xref",
      "Bugs": [
        "DSA-3499-1"
      ]
    },
    {
      "Original": "- pillow 3.1.1-1 (bug #813905)",
      "Line": 461769,
      "Type": "package",
      "Package": "pillow",
      "Kind": "fixed",
      "Version": "3.1.1-1",
      "BugNo": 813905
    },
    {
      "Original": "- python-imaging \u003cnot-affected\u003e (Vulnerable code introduce in 2.0.0)",
      "Line": 461770,
      "Type": "package",
      "Package": "python-imaging",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduce in 2.0.0"
    },
    {
      "Original": "NOTE: Issue when linked against libtiff \u003e= 4.0.0",
      "Line": 461771,
      "Type": "NOTE",
      "Description": "Issue when linked against libtiff \u003e= 4.0.0"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python-pillow/Pillow/commit/6dcbf5bd96b717c58d7b642949da8d323099928e (3.1.1)",
      "Line": 461772,
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python-pillow/Pillow/commit/6dcbf5bd96b717c58d7b642949da8d323099928e (3.1.1)"
    },
    {
      "Original": "NOTE: Introduced by: https://github.com/python-pillow/Pillow/commit/e782fe721e0156de9636e78cd881d9f9e7e6ce50 (2.0.0)",
      "Line": 461773,
      "Type": "NOTE",
      "Description": "Introduced by: https://github.com/python-pillow/Pillow/commit/e782fe721e0156de9636e78cd881d9f9e7e6ce50 (2.0.0)"
    }
  ]
}