{
  "Header": {
    "Original": "CVE-2021-30458 (An issue was discovered in Wikimedia Parsoid before 0.11.1 and 0.12.x  ...)",
    "Line": 162727,
    "ID": "CVE-2021-30458",
    "Description": "(An issue was discovered in Wikimedia Parsoid before 0.11.1 and 0.12.x  ...)"
  },
  "Annotations": [
    {
      "Original": "- mediawiki 1:1.35.2-1",
      "Line": 162728,
      "Type": "package",
      "Package": "mediawiki",
      "Kind": "fixed",
      "Version": "1:1.35.2-1"
    },
    {
      "Original": "[buster] - mediawiki \u003cnot-affected\u003e (Only applies to 1.35 and later)",
      "Line": 162729,
      "Type": "package",
      "Release": "buster",
      "Package": "mediawiki",
      "Kind": "not-affected",
      "Description": "Only applies to 1.35 and later"
    },
    {
      "Original": "[stretch] - mediawiki \u003cnot-affected\u003e (Only applies to 1.35 and later)",
      "Line": 162730,
      "Type": "package",
      "Release": "stretch",
      "Package": "mediawiki",
      "Kind": "not-affected",
      "Description": "Only applies to 1.35 and later"
    },
    {
      "Original": "NOTE: https://phabricator.wikimedia.org/T279451",
      "Line": 162731,
      "Type": "NOTE",
      "Description": "https://phabricator.wikimedia.org/T279451"
    }
  ]
}