{
  "Header": {
    "Original": "CVE-2017-12606 (OpenCV (Open Source Computer Vision Library) through 3.3 has an out-of ...)",
    "Line": 393642,
    "ID": "CVE-2017-12606",
    "Description": "(OpenCV (Open Source Computer Vision Library) through 3.3 has an out-of ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2799-1 DLA-1438-1 DLA-1117-1}",
      "Line": 393643,
      "Type": "xref",
      "Bugs": [
        "DLA-2799-1",
        "DLA-1438-1",
        "DLA-1117-1"
      ]
    },
    {
      "Original": "[experimental] - opencv 3.4.4+dfsg-1~exp1",
      "Line": 393644,
      "Type": "package",
      "Release": "experimental",
      "Package": "opencv",
      "Kind": "fixed",
      "Version": "3.4.4+dfsg-1~exp1"
    },
    {
      "Original": "- opencv 3.2.0+dfsg-6 (bug #872044)",
      "Line": 393645,
      "Type": "package",
      "Package": "opencv",
      "Kind": "fixed",
      "Version": "3.2.0+dfsg-6",
      "BugNo": 872044
    },
    {
      "Original": "NOTE: https://github.com/opencv/opencv/issues/9309",
      "Line": 393646,
      "Type": "NOTE",
      "Description": "https://github.com/opencv/opencv/issues/9309"
    }
  ]
}